# Generated by Django 4.0 on 2023-12-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='email',
        ),
        migrations.AddField(
            model_name='commande',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
