# Generated by Django 4.0 on 2023-12-25 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_commande_email_commande_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='zipcode',
        ),
    ]
